# Use lightweight Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY requirements-cloud.txt .

# Copy the rest of the application code
COPY . .
# Install dependencies
RUN pip install --no-cache-dir -r requirements-cloud.txt

# Copy application code all files except .env .git 

# Set environment variables
ENV PORT=8088
ENV HOST=0.0.0.0

# Expose the port
EXPOSE 8088
